[[agents]]
name = "kaniko"
kubernetes = "kaniko.yml"
[agents.tags]
role = "kaniko"

[[agents]]
name = "bar"
kubernetes = "job.yml"
[agents.tags]
foo = "bar"

[[agents]]
name = "baz"
kubernetes = "job.yml"
[agents.tags]
foo = "baz"
